let lessons = [
{ "id": 1, 
  "subject":"Math", 
  "location":"California", 
  "price":100, 
  "spaces":5 },
{ "id": 2, 
  "subject":"Physics", 
  "location":"Arizona", 
  "price":120, 
  "spaces":5},
{ "id": 3, 
  "subject":"Chemistry", 
  "location":"New York", 
  "price":95, 
  "spaces":5},
{ "id": 4, 
  "subject":"English", 
  "location":"Texas", 
  "price":80, 
  "spaces":5},
{ "id": 5, 
  "subject":"Art", 
  "location":"Washington D.C", 
  "price":70, 
  "spaces":5}
];